### ISSUE TITLE
OS Packager Edit Interface does not show remapping UI 

### ISSUE THREAD

**Issue by fathoni** [openbudgets/integration#16] opened 2017-08-31 10:52 UTC
@pwalsh Clicking the edit button on a particular data set within Packager admin does not lead to a page with re-mapping. See screenshot below:

![image](https://user-images.githubusercontent.com/1597027/29919797-1046f71c-8e4b-11e7-87ec-2ae0b9c43935.png)

Seems that there is a problem with the login as well since my login from the admin page is not retained.

**Comment by pwalsh** [comment] 2017-08-31 10:54
@vitorbaptista can you check?

**Comment by vitorbaptista** [comment] 2017-08-31 12:07
@fathoni Could you check again? Also, to be clear, the path you took to get to that screen was:

1. Go to your admin page
2. Click on the "edit" buttom of one of your dataset

Is that right?

**Comment by fathoni** [comment] 2017-08-31 12:42
exactly! just checked and I still have the similar issue.

**Comment by vitorbaptista** [comment] 2017-08-31 13:36
@fathoni Let's talk about this issue on Gitter. I sent you a private message over there :v:

**Comment by vitorbaptista** [comment] 2017-08-31 14:03
After talking with @fathoni over Gitter, we discovered that the issue was that his browser cached a request. A hard refresh fixed the issue :+1:

**Comment by pwalsh** [comment] 2017-08-31 14:04
@vitorbaptista @fathoni great, so I'll close this, as it is not a bug.

**Closed as completed by pwalsh** 2017-08-31 14:04 UTC
